### ISSUE TITLE
Add histogram of classes on choropleth maps 

### ISSUE THREAD

**Issue by rCarto** [riatelab/magrit#100]
or bar plot for typo. Feature request with low priority of course.

**Comment by mthh** [comment]
Very good idea, thanks !
I recently saw some maps made with mapsf that featured a beeswarm plot, and I was thinking we should go for something like that in Magrit too.

I won't link this issue to a particular milestone yet because I don't know if it should happen in the current Magrit or in a possible v2.

**Comment by mthh** [comment]
Done in the v2.
