### ISSUE TITLE
Grid transformation on "Europe NUTS2" layer - geometry2.coordinates is undefined

### ISSUE THREAD

**Issue by RCura** [riatelab/magrit#127]
After adding the Europe NUTS2 layer (example data), I tried to apply a grid (carroyage) transformation to it, using the `AREA_TOT_2024` variable, and the grid creation fails with this error : 

![image](https://github.com/riatelab/magrit/assets/807703/498fe28d-3751-4b83-8f42-a0cbdaf52715)

In the browser debug terminal : 
```
computeGriddedLayer: isGeo false ; resolution 180000 meters
```

**Comment by mthh** [comment]
cc @rysebaert 
The NUTS2 example dataset has a lot of topology issues (cf. screenshot below after NUTS2 aggregation).

![export (36)](https://github.com/riatelab/magrit/assets/12172162/4b33affa-9fb6-482e-b000-fa00554052dc)

Once they are fixed, the gridding seems to work fine with.

So the issue is two-fold: we should try to be better at handling problematic datasets (not always super easy) and we should avoid to propose example datasets with topology issues (note that the topology issues of the NUTS2 dataset can be corrected directly in Magrit in the simplification panel by adjusting the "Précision des coordonnées" parameter).

**Comment by mthh** [comment]
The handling of the reported error has been fixed.

I've also improved the topology of the dataset that triggered the error.
