### ISSUE TITLE
Zoom/scale on new layer

### ISSUE THREAD

**Issue by RCura** [riatelab/magrit#128]
When adding a new layer, Magrit remains on the previously set zoom, which might be great for some uses, but is a problem when starting from blank  : 
for example, when you open Magrit without a project and add the "Quartiers de Paris" example dataset, it feels like this isn't working as the projection is by default zoomed on a way larger extent.

For France or Europe scale data, this is no problem, but for small-areas datasets, this doesn't feel right.

Here's an example of a new project with only Paris Quartiers added : 

![image](https://github.com/riatelab/magrit/assets/807703/12e09bcd-5baa-4b2d-8fde-5ae51d198eb1)

I'm not sure if there should always be a zoom on extent when adding new layers, but this might at least be the case with a test checking if there's already another layer loaded ?

**Comment by mthh** [comment]
Thanks!

In fact, when a layer is added, if there are currently no layers, the zoom is set to fit the map to the added layer... except when adding an example dataset.

This is an oversight that will be corrected right away in the next bug fix release (so that it works the same when adding an example dataset as when adding other datasets).
