### ISSUE TITLE
Issue importing .kml data

### ISSUE THREAD

**Issue by imaneaadl** [riatelab/magrit#131]
Hello,

Hoping this message finds you well.

I have an issue importing this data set (format .kml, please find attached) onto my project. When I try import it contiuously loads without being imported (see screenshot). Is there an issue with my data set? Please answer me as you can, I need to finish this project for work as soon as possible.
Thanks for your understanding.

Best, 
Imane.

[IDE des leaders mondiaux du secteur de la santé .csv](https://github.com/user-attachments/files/16157009/IDE.des.leaders.mondiaux.du.secteur.de.la.sante.csv)

![Screenshot_magrit](https://github.com/riatelab/magrit/assets/175193300/dc9431eb-5143-4cc4-8fff-c90703566a35)

**Comment by mthh** [comment]
Thank you for your bug report.
I'm a bit confused, is the dataset you're trying to import the one put in PJ here?
Because it's a CSV dataset (not only because of its extension but also because of its content).

By importing it as a CSV file (with the .csv extension), the import works correctly for me. 

Can you try importing it as a CSV file too? (Or, in case of attachment error, can you attach the correct KML file?)

In any case, it's true that there's a small problem in the management of problematic datasets, normally (and this is the case on my computer) when a dataset is invalid, the spinner with "dataset analysis" should disappear and an error message (in a "toast") should appear at the bottom of the screen. What's you OS and your browser ?

**Comment by mthh** [comment]
There is indeed a bug when importing KML file on windows, it will be fixed very soon.
