### ISSUE TITLE
Mildly large exports (svg, project-file, geo layer) doesn't work on Chromium

### ISSUE THREAD

**Issue by JeremyG** [riatelab/magrit#16]
Trying to export a map in SVG but it doesn't work. It says "fails to download - network error" (échec - erreur réseau). I'm using Chromium under Linux Mint, and trying to download through a university network, which might be causing this somehow.

**Comment by mthh** [comment]
Hi, 
Thanks for your feedback (which I may treat as 2 different issues due to the separate process involved for this two kinds of export).

I can't reproduce this issue easily; by any chance (and if there is no private/sensitive information on what your are working of course), could you export the project (by clicking on the "floppy disk" icon up-right) which triggers theses errors and send it to me (so I may see if a particular feature is causing the SVG export to fail)?

Or maybe have you observed that the GeoJSON export is failing with a specific layer of yours ?

Thanks,
mthh

**Comment by JeremyG** [comment]
(Updated the issue name to restrict to SVG, and opened issue #17 for GeoJSON export)
I wanted to attach the project export to this comment but it failed to download too... I used the example dataset of US states, styled as a cartogram based on population, and displayed with azimuthal equal area projection, with only the Cartogram layer visible. Projection might be the source of the bug? Or visibility?

**Comment by mthh** [comment]
Thanks for the details, i'm able too reproduce it, I'm looking into it!

**Comment by mthh** [comment]
I just merged a fix, it should be updated on the public instance this night.

**Comment by JeremyG** [comment]
Great, thanks for this!
