### ISSUE TITLE
Joining data and basemap on a string field

### ISSUE THREAD

**Issue by aschoenauer-sebag** [riatelab/magrit#40]
Hi,

It would be really nice to be able to join data and basemap on a string field, say `names`, with some basic operations being performed on the field so that accents, small orthographic mistakes or punctuation differences don't influence the joint.

It could start as a joint on `func(names)` rather than `names` with 
`func = lambda x: unidecode(x.translate(str.maketrans('', '', string.punctuation)).lower().replace(' ', ''))`

As to correcting orthographic mistakes I'm not sure which package/algorithm is the best for French pronunciation - any idea? It seems like Soundex, dMetaphone or NYIIS are rather optimized for English words (for example from a quick check they match Blainville and Blonville, and don't match Brévands and Brévan).

Thanks,
Alice

**Comment by rCarto** [comment]
Hi, 

Thank you for your suggestion. 
Magrit is largely used in cartography/mapping teaching classes. One key point in teaching a mapping software is understanding the importance of the join operation and the unique identifier concept. Hence, we try to foster good practices by strongly enforce the usage of unique identifiers (ID codes instead of names for examples).
So, I'm sorry that your suggestion, which I would be happy to find in more complex mapping tools, is against these principles.

**Comment by aschoenauer-sebag** [comment]
OK, got it :) Thanks for your reply.
