### ISSUE TITLE
Adding  sample layer

### ISSUE THREAD

**Issue by mir123** [riatelab/magrit#41]
I would like to customize the list of sample base layers for a group of students. I have added TopoJSON and GeoJSON files to `magrit_app/static/data_sample`, and modified `static/json/sample_layers.json` and  `client/js/layers.js` and can't make it work.

**Comment by mthh** [comment]
Thanks for the report !

Sorry, this part of the code is not very clear (in the end there remains a place to modify in the code so that these layers are added in the interface): you have to reference theses layers in the `target_layers` variable (https://github.com/riatelab/magrit/blob/5f155963751373077c0f77b22fcf526c724b72b8/client/js/layers.js#L129) and recompile the JS code with `webpack` following the instructions (in `CONTRIBUTING.md`)
BTW you don't have to add both geojson and topojson format for the same layer, just one of them (the one referenced in `sample_layers.json`) is enough.

Don't hesitate if you're still facing issues with theses examples layers.

**Comment by mthh** [comment]
Fixed by #45.
