### ISSUE TITLE
Dorling option for proportional symbols

### ISSUE THREAD

**Issue by rysebaert** [riatelab/magrit#77]
add Dorling option for maps with proportional symbols, to avoid overlapping > would require an additional parameter (number of iterations)
![magrit2](https://user-images.githubusercontent.com/17565776/177562456-3fd4899e-d73a-4209-a79c-ec92f33e3404.PNG)

**Comment by mthh** [comment]
I have a first almost complete implementation (the simulation is restarted if the user changes the cartographic projection but I still have some details to fix to restart the simulation when the user changes the symbol size or the symbol border size)

What do you think about not asking for the number of iterations when creating the layer (and that this number can then be modified in the layer properties popup)?
Cf. screenshot below of what I propose.

Layer creation option :

![layer_creation](https://user-images.githubusercontent.com/12172162/196663795-07114118-8b2b-418e-89c5-29f930c42760.png)

Layer properties popup :

![popup_style](https://user-images.githubusercontent.com/12172162/196663767-8520c017-71d5-4271-9aa5-0723ece45454.png)

**Comment by neocarto** [comment]
Ok with that

**Comment by rCarto** [comment]
Ok for me + we should add a reference to the algorithm in documentation (that explain iterations).

**Comment by mthh** [comment]
> we should add a reference to the algorithm in documentation (that explain iterations).

Yes sure !

I chose not to refer to Dorling / Demers here (to have the same "avoid overlap" setting for square and circle and to avoid needing special cartographic knowledge when the user just wants to "avoid overlaps") and save that for the documentation.

However we could already have some info about this in a tooltip (so that the user knows that increasing the number of iterations is supposed to improve the result)?

**Comment by rCarto** [comment]
> However we could already have some info about this in a tooltip (so that the user knows that increasing the number of iterations is supposed to improve the result)?

That would be great.
