### ISSUE TITLE
problem with xls import

### ISSUE THREAD

**Issue by rCarto** [riatelab/magrit#85]
From comment under  https://magrit.hypotheses.org/75

Bonjour,

J’ai depuis hier le message suivant qui s’affiche lorsque j’essaye d’importer un jeu de données via un tableau excel :

Une erreur s’est produite – L’opération en cours a été stoppée.
Détails : Unable to convert the provided file. Please check that it is a tabular file supported by the application (in xls, xlsx, ods or csv format).

J’ai vérifié et le fichier est au bon format, et même avec seulement deux colonnes, une avec les code_insee et l’autre avec les noms de communes cela ne marche pas. Avez-vous une idée de pourquoi ?

**Comment by mthh** [comment]
I'm able to reproduce it with `xlsx` (`xls`, `ods` and `csv` are working fine). I will push / deploy a fix today.

I will also answer on https://magrit.hypotheses.org/75.

**Comment by mthh** [comment]
Just for the record, the exception that is raised in Python code is `AttributeError: 'ElementTree' object has no attribute 'getiterator'`.
Since Python 3.9 `xml.etree.ElementTree.Element.getiterator()` has been removed, but there is a way to inform `xlrd` (that is used by `pyexcel` on which we rely) about that.

**Comment by mthh** [comment]
The new version in now online on https://magrit.cnrs.fr.

**Comment by rCarto** [comment]
See https://magrit.hypotheses.org/75#comment-243
- Add a dataset 
- Import a valid csv file
- Data type button not enabled
- Add a geom layer
- Join data and geom
- Data type button enabled

It seems that the "Data type / typage des données" button is only enabled when a geom layer is present and joined to the dataset. Not sure it was the case before. 
Does it makes sense to enable data typing only when a geom layer is joined (bug or feature)?

**Comment by mthh** [comment]
To my knowledge it has always been like that.

I'm not sure I understand the problem (?), specifying the types of the fields of the ("external") data table before the join would be useless because the fields in this data table are not proposed anywhere (i.e. in the menus related to the cartographic representations).

These fields are only used in Magrit once joined to the target layer.

I think the user had simply forgotten to make a join with his geo dataset (or simply omitted the need for such a dataset).

I'm open to discuss this if I'm not understanding it correctly or if you see a need to do this typing on the data array.

**Comment by rCarto** [comment]
So feature then. I think it makes sense to keep it the way it is.
